repos:
  - repo: local
    hooks:
      - id: black
        name: Black Code Formatter
        entry: python
        args: [-m, black, --line-length=88, .]
        language: system
        types: [python]
        pass_filenames: false
      - id: isort
        name: Import Sorter
        entry: python
        args: [-m, isort, --profile=black, .]
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: Flake8 Linter
        entry: python
        args: [-m, flake8, --max-line-length=88, --extend-ignore=E203,W503, .]
        language: system
        types: [python]
        pass_filenames: false